import fixture from '@/data/claim-selection-sampling-frame-fixture.json';
import { claimSelectionSamplingDecision, type ClaimSelectionSamplingFrame, type SamplingDimension } from '@/lib/claim-selection-sampling';

const labels: Record<SamplingDimension, string> = { transcript_region: 'Episode region', speaker: 'Speaker', machine_claim_type: 'Machine label', machine_confidence: 'Confidence band' };

export function ClaimSelectionSamplingDemo() {
  const frame = fixture as ClaimSelectionSamplingFrame;
  const decision = claimSelectionSamplingDecision(frame);
  return <section className="border-t-2 border-ink bg-[#ffd76a]"><div className="mx-auto max-w-6xl px-5 py-12 md:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[9px] font-bold uppercase text-cobalt">Selection sampling frame · synthetic</p><h2 className="mt-2 max-w-4xl text-4xl font-black tracking-[-0.05em]">A convenient sample is not an audit.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-ink/60">Coverage must reach the episode's regions, speakers, candidate types, and confidence bands before precision or recall can describe extraction quality.</p></div><span className="border-2 border-ink bg-coral px-4 py-3 font-mono text-[9px] font-bold uppercase">Rates withheld</span></div><div className="mt-7 grid gap-4 lg:grid-cols-4">{(Object.keys(labels) as SamplingDimension[]).map((dimension) => <article className="border-2 border-ink bg-paper p-4" key={dimension}><p className="font-mono text-[8px] font-bold uppercase text-cobalt">{labels[dimension]}</p><div className="mt-4 space-y-3">{frame.strata.filter((stratum) => stratum.dimension === dimension).map((stratum) => { const passes = stratum.sampled_count >= stratum.required_minimum; return <div className="border-t border-ink/15 pt-3" key={stratum.stratum_id}><div className="flex justify-between gap-2 text-xs font-bold"><span>{stratum.label}</span><span className={passes ? 'text-ink' : 'text-coral'}>{stratum.sampled_count}/{stratum.required_minimum}</span></div><p className="mt-1 text-[10px] leading-relaxed text-ink/45">{stratum.coverage_note}</p></div>; })}</div></article>)}</div><div className="mt-5 grid gap-4 border-2 border-ink bg-ink p-5 text-paper lg:grid-cols-[.7fr_1.3fr]"><div><strong className="text-4xl">{frame.sampled_segment_count}/{frame.minimum_sample_size}</strong><p className="mt-1 font-mono text-[8px] font-bold uppercase text-acid">minimum sample</p><p className="mt-4 font-mono text-[7px] uppercase text-paper/35">{frame.selection_seed_digest} · {frame.sampling_method.replaceAll('_', ' ')}</p></div><div><p className="font-mono text-[8px] font-bold uppercase text-coral">Interpretation blockers</p><ul className="mt-3 space-y-2 text-xs text-paper/65">{decision.blockers.map((blocker) => <li key={blocker}>— {blocker}</li>)}</ul></div></div><p className="mt-4 font-mono text-[8px] font-bold uppercase text-ink/45">Fixture only · overlapping strata do not sum to the sample size · thresholds are methodology inputs, not universal standards</p></div></section>;
}
