import fixture from '@/data/reviewed-findings-fixture.json';
import { summarizeReviewCoverage, type ReviewedClaimFinding } from '@/lib/reviewed-findings';

const tone: Record<string, string> = { supported: 'bg-acid', mostly_supported: 'bg-acid', mixed: 'bg-[#ffd76a]', mostly_unsupported: 'bg-coral', unsupported: 'bg-coral', insufficient_evidence: 'bg-coral', disputed: 'bg-cobalt text-white', outdated: 'bg-ink/10', not_yet_resolved: 'bg-cobalt text-white', not_applicable: 'bg-ink/10' };

export function ReviewedFindingsDemo() {
  const records = fixture.records as ReviewedClaimFinding[];
  const coverage = summarizeReviewCoverage(records);
  return <section className="border-t-2 border-ink bg-cobalt text-white"><div className="mx-auto max-w-6xl px-5 py-12 md:px-10"><p className="font-mono text-[9px] font-bold uppercase text-acid">Reviewed findings · synthetic</p><div className="mt-2 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="text-4xl font-black tracking-[-0.05em]">One claim. Multiple findings.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-white/65">Factual accuracy, causal support, quantitative accuracy, framing, currency, and evidence sufficiency stay separate. Reviewer confidence is visible; it never substitutes for evidence.</p></div><div className="grid grid-cols-3 border-2 border-white/30">{[[coverage.eligible, 'eligible'], [coverage.reviewed, 'reviewed'], [`${Math.round(coverage.coverage * 100)}%`, 'coverage']].map(([value, label]) => <div className="border-r border-white/30 p-4 text-center last:border-r-0" key={label}><strong className="block text-3xl text-acid">{value}</strong><span className="font-mono text-[8px] uppercase text-white/50">{label}</span></div>)}</div></div><div className="mt-7 border-2 border-white bg-ink p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[9px] font-bold uppercase text-coral">Aggregate score hidden</p><h3 className="mt-1 text-2xl font-black">Coverage and resolution come first.</h3></div><span className="border border-acid px-3 py-2 font-mono text-[8px] font-bold uppercase text-acid">{coverage.hiddenReason}</span></div></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{records.filter((record) => record.review_state === 'editor_reviewed').map((record) => <article className="border-2 border-ink bg-paper p-5 text-ink" key={record.canonical_claim_id}><div className="flex items-center justify-between"><span className="font-mono text-[8px] font-bold uppercase text-cobalt">{record.canonical_claim_id}</span><span className="font-mono text-[8px] font-bold uppercase">Editor reviewed</span></div><div className="mt-4 space-y-3">{record.findings.map((finding) => <div className="border-t border-ink/15 pt-3" key={finding.dimension}><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm capitalize">{finding.dimension.replaceAll('_', ' ')}</strong><span className={`px-2 py-1 font-mono text-[8px] font-bold uppercase ${tone[finding.state]}`}>{finding.state.replaceAll('_', ' ')}</span></div><p className="mt-2 text-xs leading-relaxed text-ink/55">{finding.rationale}</p><p className="mt-2 font-mono text-[8px] uppercase text-ink/40">Confidence {finding.reviewer_confidence} · {finding.evidence_link_ids.length} evidence links</p></div>)}</div></article>)}</div></div></section>;
}

