import fixture from '@/data/speaker-attribution-fixture.json';
import type { SegmentAttribution, SpeakerIdentity } from '@/lib/speaker-attribution';

export function SpeakerAttributionDemo() {
  const speakers = fixture.speakers as SpeakerIdentity[];
  const attributions = fixture.attributions as SegmentAttribution[];
  const names = new Map(speakers.map((speaker) => [speaker.speaker_id, speaker.display_name]));
  return <section className="border-t-2 border-ink bg-ink text-paper"><div className="mx-auto max-w-6xl px-5 py-12 md:px-10"><p className="font-mono text-[9px] font-bold uppercase text-acid">Speaker attribution · synthetic</p><h2 className="mt-2 text-4xl font-black tracking-[-0.05em]">“Who said it?” is a finding.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-paper/60">Unknown voices stay unknown. Overlapping speech stays plural. Editor reassignments append a reasoned record instead of silently replacing the machine label.</p><div className="mt-7 grid gap-4 lg:grid-cols-3">{attributions.map((record) => <article className="border-2 border-paper/35 bg-paper p-5 text-ink" key={record.attribution_id}><div className="flex items-center justify-between gap-2"><span className="font-mono text-[8px] font-bold uppercase text-cobalt">{record.segment_id}</span><span className={`px-2 py-1 font-mono text-[7px] font-bold uppercase ${record.mode === 'unknown_speaker' ? 'bg-coral' : record.mode === 'overlapping_speech' ? 'bg-[#ffd76a]' : 'bg-acid'}`}>{record.mode.replaceAll('_', ' ')}</span></div><h3 className="mt-5 text-2xl font-black">{record.speaker_ids.length ? record.speaker_ids.map((id) => names.get(id) ?? id).join(' + ') : 'Unknown speaker'}</h3><div className="mt-3 flex flex-wrap gap-2 font-mono text-[8px] font-bold uppercase text-ink/45"><span>{record.confidence} confidence</span><span>·</span><span>{record.review_state.replaceAll('_', ' ')}</span></div>{record.revisions.map((revision) => <div className="mt-5 border-l-4 border-cobalt pl-3" key={revision.revision_number}><p className="font-mono text-[8px] font-bold uppercase text-cobalt">Reassigned · revision {revision.revision_number}</p><p className="mt-2 text-xs leading-relaxed">{revision.reason}</p><p className="mt-2 font-mono text-[7px] uppercase text-ink/40">{revision.changed_by} · {revision.changed_at.slice(0, 10)}</p></div>)}</article>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{speakers.map((speaker) => <div className="border border-paper/25 p-4" key={speaker.speaker_id}><strong className="block">{speaker.display_name}</strong><span className="mt-1 block font-mono text-[7px] uppercase text-paper/45">{speaker.identity_state} · {speaker.identity_basis.replaceAll('_', ' ')}</span></div>)}</div><p className="mt-4 font-mono text-[8px] font-bold uppercase text-paper/35">Fixture only · categorical confidence avoids false decimal precision</p></div></section>;
}
