import fixture from '@/data/analysis-history-fixture.json';
import { currentPublishedVersion, type AnalysisVersionRecord } from '@/lib/analysis-history';

export function VersionHistoryDemo() {
  const versions = fixture.versions as AnalysisVersionRecord[];
  const current = currentPublishedVersion(versions);
  return <section className="border-t-2 border-ink bg-paper"><div className="mx-auto max-w-6xl px-5 py-12 md:px-10"><p className="font-mono text-[9px] font-bold uppercase text-coral">Correction history · synthetic</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-4xl font-black tracking-[-0.05em]">Correct the record. Keep the record.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-ink/60">Transcript, attribution, grouping, evidence, and finding changes create a new immutable version. The current view updates without erasing what readers previously saw.</p></div><span className="bg-ink px-3 py-2 font-mono text-[9px] font-bold uppercase text-acid">Current: v{current?.version_number}</span></div><div className="mt-8 grid gap-0 border-2 border-ink lg:grid-cols-3">{versions.map((version, index) => <article className={`relative border-b-2 border-ink p-5 last:border-b-0 lg:border-b-0 lg:border-r-2 lg:last:border-r-0 ${version.version_id === current?.version_id ? 'bg-acid' : 'bg-white'}`} key={version.version_id}><div className="flex items-center justify-between"><span className="font-mono text-[9px] font-bold uppercase text-cobalt">Version {version.version_number}</span><span className="font-mono text-[8px] uppercase text-ink/40">{version.review_state}</span></div><h3 className="mt-5 text-lg font-black leading-tight">{version.change_summary}</h3><div className="mt-4 flex flex-wrap gap-1">{version.change_kinds.map((kind) => <span className="border border-ink/20 px-2 py-1 font-mono text-[7px] font-bold uppercase" key={kind}>{kind.replaceAll('_', ' ')}</span>)}</div><p className="mt-4 font-mono text-[8px] uppercase text-ink/40">{version.created_at.slice(0, 10)} · {version.changed_record_ids.length} records</p>{index > 0 ? <p className="mt-2 font-mono text-[7px] text-ink/35">Parent: {version.parent_version_id}</p> : null}</article>)}</div><p className="mt-4 font-mono text-[8px] font-bold uppercase text-ink/40">Fixture only · prior versions remain addressable · no real correction represented</p></div></section>;
}

