'use client';

import { ArrowLeft, FlaskConical, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import fixture from '@/extension/data/synthetic-youtube-fixture.json';
import registry from '@/extension/data/analyses.json';

export function EpisodeAnalysis() {
  const [entityKey, setEntityKey] = useState<string | null>(null);
  useEffect(() => setEntityKey(new URLSearchParams(window.location.search).get('entity_key')), []);
  const analysis = registry.analyses.find((entry) => entry.entity_key === entityKey);
  const available = entityKey === fixture.entity_key && analysis?.status === 'published' && analysis.publication_state === 'active';

  return <main className="min-h-screen bg-paper text-ink">
    <header className="border-b-2 border-ink px-5 py-5 md:px-10"><div className="mx-auto flex max-w-6xl items-center justify-between"><a className="inline-flex items-center gap-2 font-mono text-[9px] font-bold uppercase" href="https://ai.rhyslindmark.com/claims"><ArrowLeft className="h-4 w-4" /> AI Claims</a><span className="font-mono text-[9px] font-bold uppercase text-cobalt">YouTube episode analysis</span></div></header>
    <section className="border-b-2 border-ink bg-ink text-paper"><div className="mx-auto max-w-6xl px-5 py-12 md:px-10"><div className="inline-flex items-center gap-2 border border-acid px-3 py-2 font-mono text-[9px] font-bold uppercase text-acid"><FlaskConical className="h-4 w-4" /> Synthetic end-to-end fixture</div><h1 className="mt-5 text-5xl font-black leading-[.9] tracking-[-.065em] md:text-7xl">YOUTUBE →<br /><span className="text-acid">EVIDENCE.</span></h1><p className="mt-5 max-w-2xl text-sm leading-relaxed text-paper/60">A fake video proves page detection, canonical identity, resolver gating, scoring, and a dedicated episode trail without judging a real person or podcast.</p></div></section>
    {available ? <>
      <section className="mx-auto grid max-w-6xl gap-4 px-5 py-10 md:px-10 lg:grid-cols-[.7fr_1.3fr]">
        <article className="border-2 border-ink bg-acid p-6 shadow-[6px_6px_0_#1c1c1a]"><div className="flex items-center gap-2 font-mono text-[8px] font-bold uppercase text-cobalt"><ShieldCheck className="h-4 w-4" /> Fully reviewed fixture</div><p className="mt-7 text-xs font-black uppercase">Fixture truth score</p><p className="text-8xl font-black leading-none tracking-[-.09em] text-cobalt">{analysis.score_0_100}<span className="text-2xl tracking-normal">/100</span></p><p className="mt-5 font-mono text-[8px] font-bold uppercase leading-relaxed">{analysis.reviewed_claims}/{analysis.eligible_claims} eligible claims reviewed · {analysis.unresolved_claims} unresolved · method {analysis.methodology_version}</p></article>
        <article className="border-2 border-ink bg-white p-6"><p className="font-mono text-[9px] font-bold uppercase text-coral">Canonical path</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><div className="border border-ink/20 p-3"><span className="font-mono text-[7px] uppercase text-ink/40">Fake page</span><strong className="mt-1 block break-all text-xs">{fixture.canonical_url}</strong></div><div className="border border-ink/20 p-3"><span className="font-mono text-[7px] uppercase text-ink/40">Entity</span><strong className="mt-1 block break-all text-xs">{fixture.entity_key}</strong></div><div className="border border-ink/20 p-3"><span className="font-mono text-[7px] uppercase text-ink/40">Analysis version</span><strong className="mt-1 block text-xs">{analysis.analysis_version_id}</strong></div><div className="border border-ink/20 p-3"><span className="font-mono text-[7px] uppercase text-ink/40">Reviewed</span><strong className="mt-1 block text-xs">{analysis.last_reviewed_at}</strong></div></div><p className="mt-5 border-t border-ink/15 pt-4 text-xs leading-relaxed text-ink/55">{fixture.fixture_notice}</p></article>
      </section>
      <section className="border-t-2 border-ink bg-white"><div className="mx-auto max-w-6xl px-5 py-10 md:px-10"><p className="font-mono text-[9px] font-bold uppercase text-cobalt">Timestamped claim trail</p><div className="mt-6 grid gap-3 lg:grid-cols-2">{fixture.claims.map((claim) => { const segment = fixture.transcript_segments.find((item) => item.segment_id === claim.segment_id)!; return <article className="border-2 border-ink bg-paper p-5" key={claim.claim_id}><div className="flex justify-between gap-3 font-mono text-[8px] font-bold uppercase"><span>{Math.floor(segment.start_seconds / 60)}:{String(segment.start_seconds % 60).padStart(2, '0')} · {claim.claim_type}</span><span className={claim.verdict === 'accurate' ? 'text-cobalt' : 'text-coral'}>{claim.verdict}</span></div><blockquote className="mt-4 text-lg font-black leading-tight">“{segment.text}”</blockquote><p className="mt-4 border-t border-ink/15 pt-3 font-mono text-[8px] uppercase text-ink/45">Evidence: {fixture.evidence_records.find((record) => record.evidence_id === claim.evidence_ids[0])?.title} · credit {claim.truth_credit}</p></article>; })}</div><p className="mt-5 font-mono text-[8px] font-bold uppercase text-ink/40">Closed synthetic evidence packet · no real transcript, speaker, or world claim</p></div></section>
    </> : <section className="mx-auto max-w-4xl px-5 py-16 md:px-10"><article className="border-2 border-ink border-l-[12px] border-l-coral bg-white p-6"><p className="font-mono text-[9px] font-bold uppercase text-coral">No episode fixture</p><h2 className="mt-3 text-4xl font-black">NOT ANALYZED YET</h2><p className="mt-4 text-sm text-ink/60">This dedicated route only publishes an episode when its canonical YouTube entity passes the shared reviewed-state gate.</p></article></section>}
  </main>;
}
